# Frontend Dockerfile (ipam-frontend/Dockerfile.frontend)

FROM node:18-slim

RUN apt-get update && apt-get install -y iputils-ping && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json ./
RUN npm install

COPY . ./

CMD ["npm", "run", "dev"]
