services:
  ipam:
    container_name: ipam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ipam_data/:/data
    restart: unless-stopped
    networks:
      - ipam_net

networks:
  ipam_net:
    driver: bridge
